# Generated by Django 4.2.17 on 2024-12-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-cost'], 'verbose_name': 'Список игр'},
        ),
        migrations.AlterField(
            model_name='game',
            name='buyer',
            field=models.ManyToManyField(blank=True, related_name='games', to='task1.buyer'),
        ),
    ]
